In [ ]:
"""
Implementasi SPK kepada sebuah Universitas berdasarkan nilai akademik saat SMA yang menjadi acuan atau keputusan 
untuk masuk ke universitas di Bali

Sistem ini berasal dari sebuah Jurnal bernama :
Decision Support System for the Selection of Courses in the Higher Education using the 
Method of Elimination Et Choix Tranduit La Realite (ELECTRE)

""" 

In [ ]:
"""
Namun berhubung ingin menjelaskan sesuai yang ada pada jurnal tersebut maka diberikan contoh jika
mahasiswa yarsi memiliki sistem untuk pengambilan keputusan mahasiswa yang ingin masuk kedalam Universitas YARSI

Sistem untuk Mahasiswa Kedokteran atau Gigi yang masuk ke YARSI
Kriteria yang mungkin diberikan :

* Tes Pertama (Tes Kemampuan Dasar Akademik)
1. Matematika
2. Kimia
3. Fisika
4. Biologi

* Tes Kedua
5. Tes Bakat
6. Kemampuan serta Tes Kesehatan Lanjutan

* Kriteria tambahan cukup penting untuk penyelesaian kuliah
7. Kapasitas ekonomi per 1 semester

"""

In [ ]:
"""
Maka setiap nilai akan direpresentasikan sebagai berikut :
5 = nilai sangat bagus
4 = nilai bagus
3 = nilai yang cukup
2 = nilai buruk
1 = nilai sangat buruk

Data input dari pengguna (nilai kartu laporan) dikonversi menjadi bobot preferensi berdasarkan pada
kondisi berikut. (Semua Test Pertama dan Salah satu Test Kedua : Bakat)
- Jika nilainya berada di kisaran 85 hingga 100, maka bobot preferensi adalah 5.
- Jika nilainya berada di kisaran 80 hingga 84, maka bobot preferensi adalah 4.
- Jika nilainya berada di kisaran 75 hingga 79, maka bobot preferensi adalah 3.
- Jika nilainya berada di kisaran 65 hingga 74, maka bobot preferensi adalah 2.
- Jika nilainya berada dalam kisaran 10 hingga 64, maka bobot preferensi adalah 1.

(Salah satu Test Kedua : Kemampuan serta Tes Kesehatan Lanjutan)
- Jika lolos test Pengecekan Darah | Urine | Buta Warna | Kesehatan Gigi | Kesehatan Paru - Paru, maka bobot preferensi adalah 5.
- Jika lolos test Pengecekan Darah | Urine | Buta Warna | Kesehatan Paru - Paru, maka bobot preferensi adalah 4.
- Jika lolos test Pengecekan Darah | Urine | Buta Warna, maka bobot preferensi adalah 3.
- Jika lolos test Pengecekan Darah | Urine, maka bobot preferensi adalah 2.
- Jika lolos test Pengecekan Darah, maka bobot preferensi adalah 1.

Kemampuan ekonomi per 1 semester pengguna juga dikonversi menjadi bobot preferensi berdasarkan
kondisi berikut.
- Jika nilainya berada di kisaran Rp.450.000.000,00 hingga Rp.550.000.000,00 maka bobot preferensi adalah 5.
- Jika nilainya berada di kisaran Rp.300.000.000,00 hingga Rp.400.000.000,00 maka bobot preferensi adalah 4.
- Jika nilainya berada di kisaran Rp.100.000.000,00 hingga Rp.250.000.000,00 maka bobot preferensi adalah 3.
- Jika nilainya berada di kisaran Rp. 50.000.000,00 hingga Rp. 90.000.000,00 maka bobot preferensi adalah 2.
- Jika nilainya berada di kisaran Rp. 10.000.000,00 hingga Rp. 30.000.000,00 maka bobot preferensi adalah 1.

"""

In [71]:
# Begin to code

import pandas as pd
import numpy as np
from pandas import ExcelWriter
from pandas import ExcelFile
import math

In [ ]:
# Baca dari file external yang telah diberikan
pd.read_excel('penilaian test.xlsx')

In [2]:
# Pada Gelombang Pertama maka akan ada perubahan atau konversi dari 1 - 5 sesuai aturan
# Pada kriteria : Matematika, Kimia, Fisika, Biologi
test_gelombang_one = pd.read_excel('penilaian test tahap pertama.xlsx')

In [10]:
# Dapatkan Header alias Nama setiap file
tA = pd.read_excel('penilaian test tahap pertama.xlsx').columns
print(tA.values[1:])

print()

# Dapatkan Column disetiap atau Kriterianya
tB = test_gelombang_one.iloc[:,0].values
print(tB)

['Anda' 'Aman' 'Santi' 'Santo' 'Bambang' 'Ester' 'Andi' 'Kunto' 'Aji'
 'Maling']

['Matematika' 'Kimia' 'Fisika' 'Biologi']


In [ ]:
# Pada Gelombang Kedua maka akan ada perubahan atau konversi dari 1 - 5 sesuai aturan
# Pada kriteria : Test Bakat dan Test Kesehatan
pd.read_excel('penilaian test tahap kedua.xlsx')

In [4]:
def conversionAllNumberInput(conversion):
    # Conversion for every number of test
    if 85 <= conversion <= 100:
        return 5
    elif 80 <= conversion <= 84:
        return 4
    elif 75 <= conversion <= 79:
        return 3
    elif 65 <= conversion <= 74:
        return 2
    elif 10 <= conversion <= 64:
        return 1
    else:
        return 1

In [5]:
# Ambil seluruh data dan lakukan konversi
print(test_gelombang_one.iloc[:, 1:])
dataTestValues = test_gelombang_one.iloc[:, 1:].values
dataTest = test_gelombang_one.iloc[:, 1:].values

print()        
print(dataTestValues)

# Konversi seluruh data sesuai range yang sudah ditentukan
for i in range(len(dataTestValues)) :  
    for j in range(len(dataTestValues[i])) :
        dataTestValues[i][j] = conversionAllNumberInput(dataTestValues[i][j])

print()        
print(dataTestValues)

   Anda  Aman  Santi  Santo  Bambang  Ester  Andi  Kunto  Aji  Maling
0    80    90     90    100       70     59    47     68   94      21
1    79    70     66     45       80     88    34     77   56      13
2    70    77     67     66       77     79    67     78   46      33
3    60    67     60     77       62     69    68     77   65      66

[[ 80  90  90 100  70  59  47  68  94  21]
 [ 79  70  66  45  80  88  34  77  56  13]
 [ 70  77  67  66  77  79  67  78  46  33]
 [ 60  67  60  77  62  69  68  77  65  66]]

[[4 5 5 5 2 1 1 2 5 1]
 [3 2 2 1 4 5 1 3 1 1]
 [2 3 2 2 3 3 2 3 1 1]
 [1 2 1 3 1 2 2 3 2 2]]


In [19]:
# Simpan menjadi sebuah file Excel
dftA = pd.DataFrame(tA)
dftA = dftA.transpose()
dftB = pd.DataFrame(tB)
dfConversion = pd.DataFrame(dataTestValues)
writer = ExcelWriter('Result\konversi penilaian.xlsx')
dftA.to_excel(writer,'Sheet1',index=False,header=False)
dftB.to_excel(writer,'Sheet1',index=False,header=False,startrow=1)
dfConversion.to_excel(writer,'Sheet1',index=False,header=False,startrow=1,startcol=1)
writer.save()

In [ ]:
"""
Setelah melakukan konversi lalu mulai mengerjakan proses dari bagian teknik menggunakan metode ELECTRE
1. Perbandingan Berpasangan Ternormalisasi
"""

In [214]:
# Hasil yang nilai yang telah dikonversikan
test_gelombang_one_conversion = pd.read_excel('Result\konversi penilaian.xlsx')
print(test_gelombang_one_conversion.iloc[:, 1:])

   Anda  Aman  Santi  Santo  Bambang  Ester  Andi  Kunto  Aji  Maling
0     4     5      5      5        2      1     1      2    5       1
1     3     2      2      1        4      5     1      3    1       1
2     2     3      2      2        3      3     2      3    1       1
3     1     2      1      3        1      2     2      3    2       2


In [215]:
# Simpan Data untuk Selanjutnya
saveTestConversion = test_gelombang_one_conversion.iloc[:, 1:].values
saveTest = test_gelombang_one_conversion.iloc[:, 1:].values
print(saveTest)

# Buat Sistem menjadi list multidimensional
jumlahRow = test_gelombang_one_conversion.count(axis = 1)[1] - 1
jumlahColumn = test_gelombang_one_conversion.count(axis = 0)[1]
saveDataTest = [[0] * jumlahRow for i in range(jumlahColumn)]
print(saveDataTest)

[[4 5 5 5 2 1 1 2 5 1]
 [3 2 2 1 4 5 1 3 1 1]
 [2 3 2 2 3 3 2 3 1 1]
 [1 2 1 3 1 2 2 3 2 2]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [216]:
# Dapatkan Nilai Sum Pangkat dan Akar kuadratnya
listSumSQRT = []
jumlahOrangTest = test_gelombang_one_conversion.count(axis = 1)[1] - 1

for i in range(jumlahOrangTest):
    countSementara = 0
    dataTestConversionNew = test_gelombang_one_conversion.iloc[:,i+1].values
    for i in range(len(dataTestConversionNew)) :
        countSementara += dataTestConversionNew[i] ** 2
    listSumSQRT.append( math.sqrt(countSementara) )    

print(listSumSQRT)

[5.477225575051661, 6.48074069840786, 5.830951894845301, 6.244997998398398, 5.477225575051661, 6.244997998398398, 3.1622776601683795, 5.5677643628300215, 5.5677643628300215, 2.6457513110645907]


In [217]:
# Lalu setiap nilai akan dibagi dengan hasil turunan per column dari nilai sum per pangkat dan di kuadratkan
nilaiPembagi = 0
for i in range(len(saveTest)) :
    nilaiPembagi = listSumSQRT[i]
    for j in range(len(saveTest[i])) :
        saveDataTest[i][j] = saveTest[i][j] / nilaiPembagi

In [218]:
print(saveTest)
print()
print(saveDataTest)

[[4 5 5 5 2 1 1 2 5 1]
 [3 2 2 1 4 5 1 3 1 1]
 [2 3 2 2 3 3 2 3 1 1]
 [1 2 1 3 1 2 2 3 2 2]]

[[0.7302967433402214, 0.9128709291752769, 0.9128709291752769, 0.9128709291752769, 0.3651483716701107, 0.18257418583505536, 0.18257418583505536, 0.3651483716701107, 0.9128709291752769, 0.18257418583505536], [0.4629100498862757, 0.3086066999241838, 0.3086066999241838, 0.1543033499620919, 0.6172133998483676, 0.7715167498104595, 0.1543033499620919, 0.4629100498862757, 0.1543033499620919, 0.1543033499620919], [0.34299717028501764, 0.5144957554275265, 0.34299717028501764, 0.34299717028501764, 0.5144957554275265, 0.5144957554275265, 0.34299717028501764, 0.5144957554275265, 0.17149858514250882, 0.17149858514250882], [0.16012815380508713, 0.32025630761017426, 0.16012815380508713, 0.48038446141526137, 0.16012815380508713, 0.32025630761017426, 0.32025630761017426, 0.48038446141526137, 0.32025630761017426, 0.32025630761017426]]


In [219]:
# Simpan menjadi sebuah file Excel dari Normalized
dftA = pd.DataFrame(tA)
dftA = dftA.transpose()
dftB = pd.DataFrame(tB)
dfSaveDataTest = pd.DataFrame(saveDataTest)
writer = ExcelWriter('Result\\normalized penilaian.xlsx')
dftA.to_excel(writer,'Sheet1',index=False,header=False)
dftB.to_excel(writer,'Sheet1',index=False,header=False,startrow=1)
dfSaveDataTest.to_excel(writer,'Sheet1',index=False,header=False,startrow=1,startcol=1)
writer.save()

In [ ]:
"""
Setelah melakukan normalisasi terhadap seluruh nilai maka akan lanjut melakukan proses weight dari seluruh nilai
1. Menentukan Bobot tiap-tiap Kriteria
2. Membentuk Matrik Preferensi
"""

In [220]:
"""
Karena setiap kriteria ('Matematika' 'Kimia' 'Fisika' 'Biologi') harus memiliki bobot
berhubung karena bobot setiap test semua kemungkinan sama maka akan sedikit perkiraan saja
Matematika bobot nya : 2
Kimia bobotnya : 3
Fisika bobotnya : 2
Biologi bobotnya : 7
""" 
bobotCriteria = [2,3,2,7] # Penentuan bobot

# New List multidimensional
jumlahRow = test_gelombang_one_conversion.count(axis = 1)[1] - 1
jumlahColumn = test_gelombang_one_conversion.count(axis = 0)[1]
weightNormalized = [[0] * jumlahRow for i in range(jumlahColumn)]
print(weightNormalized)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [221]:
# Menentukan dan melakukan Weighting the normalized pada matrix normalisasi yang sudah dibuat
nilaiCriteria = 0
for i in range(len(saveDataTest)) :
    nilaiCriteria = bobotCriteria[i]
    for j in range(len(saveTest[i])) :
        weightNormalized[i][j] = saveDataTest[i][j] * nilaiCriteria
        if(j == 9):
            print(str(saveDataTest[i][j])+" x "+str(nilaiCriteria)+" = "+str(weightNormalized[i][j]))

0.18257418583505536 x 2 = 0.3651483716701107
0.1543033499620919 x 3 = 0.4629100498862757
0.17149858514250882 x 2 = 0.34299717028501764
0.32025630761017426 x 7 = 2.24179415327122


In [222]:
# Simpan ke Excel untuk hasil normalisasi weighting
dftA = pd.DataFrame(tA)
dftA = dftA.transpose()
dftB = pd.DataFrame(tB)
dfWeightNormalized = pd.DataFrame(weightNormalized)
writer = ExcelWriter('Result\\weighting normalized penilaian.xlsx')
dftA.to_excel(writer,'Sheet1',index=False,header=False)
dftB.to_excel(writer,'Sheet1',index=False,header=False,startrow=1)
dfWeightNormalized.to_excel(writer,'Sheet1',index=False,header=False,startrow=1,startcol=1)
writer.save()